[build]
  publish = "_site"
  command = "npm run build"

[[redirects]]
  from = "/travelogues"
  to = "https://old.shreyasgokhale.com/travelogues"
  status = 301
  force = false

[[redirects]]
  from = "/tech-blog"
  to = "https://old.shreyasgokhale.com/tech-blog"
  status = 301
  force = false

[[redirects]]
  from = "/faq-eit-digital-masters"
  to = "https://old.shreyasgokhale.com/faq-eit-digital-masters"
  status = 301
  force = false


[[redirects]]
  from = "/tech-blog/*"
  to = "https://old.shreyasgokhale.com/tech-blog/:splat"
  status = 301
  force = false

[[redirects]]
  from = "/travelogues/*"
  to = "https://old.shreyasgokhale.com/travelogues/:splat"
  status = 301
  force = false